version: "3.7"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "strong!Password"
      ACCEPT_EULA: "Y"

  # auth:
  #   container_name: tayra-auth
  #   build:
  #     context: .
  #     dockerfile: src/Auth/Dockerfile
  #   ports:
  #     - 443:4000
  #   restart: on-failure
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443
  #   depends_on:
  #     - sql-server-db
